const formData = [
  {
    label: 'HES',
    name: 'customfields.institute',
    value: 'HES',
    universities: [
      {
        label: 'SPU',
        name: 'customfields.university_name',
        value: 'SPU',
        fields: [
          {
            key: 'radio',
            label: 'Want to send Fee Receipt',
            id: 'Send',
            name: 'customfields.sendfeereceipt',
            type: 'radio',
            options: ['yes', 'no'],
          },
          {
            key: 'studentId',
            name: 'lead_id',
            label: 'StudentID',
            place: 'StudentID',
            id: 'StudentID',
            type: 'studentId',
          },
          {
            key: 'studentName',
            name: 'full_name',
            label: 'Student Name',
            place: 'Student Name',
            id: 'SGVUStudentName',
            type: 'text',
          },
          {
            key: 'email',
            label: 'Email-id',
            place: 'Enter Email-id',
            name: 'contact.email',
            id: 'EmailID',
            type: 'email',
          },
          {
            key: 'phone',
            label: 'phone',
            name: 'contact.phone',
            place: 'Enter Phone Number',
            id: 'phone',
            type: 'tel',
          },
          {
            key: 'father_name',
            label: 'Father Name',
            name: 'customfields.father_name',
            place: 'Enter Father Name',
            id: 'Father Name',
            type: 'text',
          },
          {
            key: 'mother_name',
            label: 'Mother Name',
            name: 'customfields.mother_name',
            place: 'Enter Mother Name',
            id: 'mother_name',
            type: 'text',
          },
          {
            key: 'session',
            label: 'Session',
            name: 'customfields.session',
            place: 'eg: 2020-2023',
            id: 'Session',
            type: 'number',
          },
          {
            key: 'sessionType',
            label: 'Session Type',
            name: 'customfields.sessionType',
            id: 'SessionType',
            place: 'Enter Session Type',
            type: 'select',
            options: ['January', 'July', 'N/A'],
          },
          {
            key: 'course',
            label: 'Course Name',
            name: 'education.course',
            id: 'course',
            place: 'Enter Course Name',
            type: 'select',
            options: ['MBA', 'BBA', 'B.Sc'],
          },
          {
            key: 'specialization',
            label: 'Specialization',
            name: 'education.specialization',
            place: 'Enter Specialization',
            id: 'Specialization',
            type: 'text',
          },
          {
            key: 'dob',
            label: 'Date of Birth',
            name: 'customfields.dob',
            place: 'Enter Date of Birth',
            id: 'dob',
            type: 'date',
          },
          {
            key: 'gender',
            label: 'Gender',
            name: 'customfields.gender',
            id: 'Gender',
            place: 'Gender',
            type: 'select',
            options: ['Male', 'Female', 'Other'],
          },
          {
            key: 'installmentType',
            label: 'Installment Type',
            id: 'InstallmentType',
            name: 'customfields.installmentType',
            place: 'Installment Type',
            type: 'select',
            options: [
              '1st Installment',
              '2nd Installment',
              '3rd Installment',
              '4th Installment',
              '5th Installment',
            ],
          },
          {
            key: 'paymentMode ',
            label: 'Payment mode ',
            name: 'customfields.paymentMode',
            id: 'PaymentMode ',
            type: 'select',
            options: ['DES Bank Account/UPI', 'University Bank Account', 'PayUMoney', 'Cash/DD'],
          },
          {
            key: 'totalPaidAmount',
            label: 'Total Paid Amount',
            name: 'customfields.totalPaidAmount',
            place: 'eg: 20000',
            id: 'Total Paid Amount',
            type: 'number',
          },
          {
            key: 'paidAmount',
            label: 'Paid Amount',
            name: 'customfields.paidAmount',
            place: 'eg: 20000',
            id: 'Paid Amount',
            type: 'number',
          },
          {
            key: 'duefeeAmount',
            label: 'Due Fee Amount',
            place: 'eg: 20000',
            name: 'customfields.duefeeAmount',
            id: 'Due Fee Amount',
            type: 'number',
          },
          {
            key: 'counselorEmail',
            label: 'Counselor Email',
            name: 'customfields.counselorEmail',
            place: 'Enter Counselor Email',
            id: 'CounselorEmail',
            type: 'email',
          },
        ],
      },
    ],
  },
  {
    label: 'DES',
    value: 'DES',
    universities: [],
  },
];

export default formData;
